4.22: Fix dtk build
Since including 9.8 repos in rhcos, dtk builds have been failing like
this:

```
error: Could not depsolve transaction; 1 problem detected:
 Problem: problem with installed package gcc-11.5.0-14.el9.x86_64
  - package redhat-rpm-config-210-1.el9.noarch from hermeto-525902 requires (annobin if (gcc or clang)), but none of the providers can be installed
  - package kernel-rpm-macros-185-14.el9.noarch from hermeto-525902 requires redhat-rpm-config >= 13, but none of the providers can be installed
  - package annobin-12.98-2.el9.x86_64 from hermeto-525902 requires libLLVM.so.21.1()(64bit), but none of the providers can be installed
  - package annobin-12.98-2.el9.x86_64 from hermeto-525902 requires libLLVM.so.21.1(LLVM_21.1)(64bit), but none of the providers can be installed
  - conflicting requests
  - nothing provides llvm-filesystem(x86-64) = 21.1.7-1.el9 needed by llvm-libs-21.1.7-1.el9.x86_64 from hermeto-525902
 ```

This configuration works in 4.23, so trying it out in 4.22